import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { prisma } from '$lib/server/db.js';
import { runLighthouseAudit } from '$lib/server/lighthouse.js';

const AUDIT_COST = 5;

export const POST: RequestHandler = async ({ request, locals }) => {
  const user = locals.user;
  if (!user) {
    return json({ error: 'Not authenticated' }, { status: 401 });
  }

  const body = (await request.json()) as { url?: string };
  const url = typeof body.url === 'string' ? body.url.trim() : '';

  if (!url) {
    return json({ error: 'URL is required' }, { status: 400 });
  }

  try {
    await prisma.$transaction(async (tx) => {
      const currentUser = await tx.user.findUniqueOrThrow({
        where: { id: user.id },
      });
      if (currentUser.credits < AUDIT_COST) {
        throw new Error('Insufficient credits');
      }
      await tx.user.update({
        where: { id: user.id },
        data: { credits: { decrement: AUDIT_COST } },
      });
      await tx.transaction.create({
        data: {
          userId: user.id,
          amount: -AUDIT_COST,
          reason: 'audit',
          balanceAfter: currentUser.credits - AUDIT_COST,
        },
      });
    });

    const auditResult = await runLighthouseAudit(url);

    await prisma.audit.create({
      data: {
        userId: user.id,
        url,
        performance: auditResult.performance,
        seo: auditResult.seo,
        accessibility: auditResult.accessibility,
        bestPractices: auditResult.bestPractices,
        lighthouseJson: auditResult.raw as object,
      },
    });

    const reportHtml = `
<div class="cs-report">
  <div class="cs-header">
    <h2>ClearSky Quick Audit Report</h2>
    <p class="cs-url">URL Analyzed: ${url}</p>
  </div>
  <div class="cs-score-section">
    <div class="cs-score-card">
      <span class="label">Performance</span>
      <span class="value">${auditResult.performance}%</span>
    </div>
    <div class="cs-score-card">
      <span class="label">SEO</span>
      <span class="value">${auditResult.seo}%</span>
    </div>
    <div class="cs-score-card">
      <span class="label">Best Practices</span>
      <span class="value">${auditResult.bestPractices}%</span>
    </div>
    <div class="cs-score-card">
      <span class="label">Accessibility</span>
      <span class="value">${auditResult.accessibility}%</span>
    </div>
  </div>
  <div class="cs-overall">
    <h3>Overall Score</h3>
    <p class="score">${Math.round(
      (auditResult.performance +
        auditResult.seo +
        auditResult.bestPractices +
        auditResult.accessibility) /
        4
    )}%</p>
    <p class="explanation">This score reflects Lighthouse-based performance, SEO readiness, accessibility, and technical health.</p>
  </div>
  <div class="cs-footer">
    <p>Generated by ClearSky Quick Audit</p>
  </div>
</div>
`;

    return json({
      html: reportHtml,
      scores: {
        performance: auditResult.performance,
        seo: auditResult.seo,
        bestPractices: auditResult.bestPractices,
        accessibility: auditResult.accessibility,
      },
      creditsRemaining: user.credits - AUDIT_COST,
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Audit failed to run';
    if (message === 'Insufficient credits') {
      return json({ error: 'Insufficient credits' }, { status: 402 });
    }
    console.error('Audit failed:', err);
    return json({ error: 'Audit failed to run' }, { status: 500 });
  }
};
